Repository CUK-LikeLion-Common/Evaluation-Lecture-team10, pull requests merged in 2023-07, with the labels that each got.

#2 [Feat/#1] 기능 개발 이슈 작성 예시
  README.md
Labels: feat

#17 [UI] 글쓰기 페이지 UI 구현
  package-lock.json
  package.json
  src/components/Write/StarRating.jsx
  src/components/Write/WriteBox.jsx
  src/pages/Write.jsx
Labels: UI

#20 gitignore 기초코드 수정
  .gitignore
  src/main/resources/application.properties
Labels: 이해송

#23 [UI] 디테일 페이지 UI 구현
  src/components/Detail/DetialBox.jsx
  src/pages/Detail.jsx
Labels: UI, 정서연

#31 [Feat/#24] 로그인/로그아웃 JSON 수정
  .DS_Store
  pom.xml
  src/main/java/com/example/lectureevaluationdev/LectureEvaluationDevApplication.java
  src/main/java/com/example/lectureevaluationdev/controller/evaluation/EvaluationController.java
  src/main/java/com/example/lectureevaluationdev/controller/likey/LikeyController.java
  src/main/java/com/example/lectureevaluationdev/controller/user/UserController.java
  src/main/java/com/example/lectureevaluationdev/dto/user/UserDTO.java
  src/main/java/com/example/lectureevaluationdev/entity/user/UserEntity.java
  src/main/java/com/example/lectureevaluationdev/log4jdbc.log4j2.properties
  src/main/java/com/example/lectureevaluationdev/repository/user/UserRepository.java
  src/main/java/com/example/lectureevaluationdev/service/evaluation/EvaluationService.java
  src/main/java/com/example/lectureevaluationdev/service/likey/LikeyService.java
  src/main/java/com/example/lectureevaluationdev/service/user/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/login.html
  src/main/resources/templates/logout.html
Labels: feat, 박지원

#34 [Feat/#22]글 작성
  hacksql.sql
  pom.xml
  src/main/java/com/example/lectureevaluationdev/controller/evaluation/EvaluationController.java
  src/main/java/com/example/lectureevaluationdev/controller/user/UserController.java
  src/main/java/com/example/lectureevaluationdev/dto/evaluation/EvaluationDTO.java
  src/main/java/com/example/lectureevaluationdev/dto/likey/LikeyDTO.java
  src/main/java/com/example/lectureevaluationdev/entity/evaluation/EvaluationEntity.java
  src/main/java/com/example/lectureevaluationdev/entity/likey/LikeyEntity.java
  src/main/java/com/example/lectureevaluationdev/mapper/GenericMapper.java
  src/main/java/com/example/lectureevaluationdev/mapper/evaluation/EvaluationMapper.java
  src/main/java/com/example/lectureevaluationdev/repository/evaluation/EvaluationRepository.java
  src/main/java/com/example/lectureevaluationdev/repository/likey/LikeyRepository.java
  src/main/java/com/example/lectureevaluationdev/service/evaluation/EvaluationService.java
  src/main/resources/application.properties
Labels: feat, 이해송

#40 [UI] 메인 화면 코드 수정
  package-lock.json
  package.json
  src/components/Main/LikeBox.jsx
  src/pages/Main.jsx
Labels: UI, 이혜영

#48 [UI] Header/Footer UI 구현
  src/App.css
  src/App.jsx
  src/components/Detail/DetailBox.jsx
  src/img/symbol.png
  src/pages/Detail.jsx
  src/shared/Footer.jsx
  src/shared/Header.jsx
Labels: UI, 정서연

#50 [Fix/#49] 글 작성 세션 수정
  src/main/java/com/example/lectureevaluationdev/controller/evaluation/EvaluationController.java
  src/main/java/com/example/lectureevaluationdev/mapper/likey/LikeyMapper.java
  src/main/resources/application.properties
Labels: bug, 이해송

#51 [Feat/#41] 게시글 추천 기능
  .gitignore
  Dockerfile
  src/main/java/com/example/lectureevaluationdev/controller/likey/LikeyController.java
  src/main/java/com/example/lectureevaluationdev/mapper/evaluation/EvaluationMapper.java
  src/main/java/com/example/lectureevaluationdev/mapper/likey/LikeyMapper.java
  src/main/java/com/example/lectureevaluationdev/repository/evaluation/EvaluationRepository.java
  src/main/java/com/example/lectureevaluationdev/repository/likey/LikeyRepository.java
  src/main/java/com/example/lectureevaluationdev/service/likey/LikeyService.java
  src/main/resources/application.properties
Labels: feat, 이해송

#59 [CI/CD] Create maven_build.yaml
  .github/workflows/maven_build.yaml
Labels: CI/CD

#70 [Fix/#69] 글 작성 본인확인 기능 수정
  src/main/java/com/example/lectureevaluationdev/controller/evaluation/EvaluationController.java
  target/classes/com/example/lectureevaluationdev/controller/evaluation/EvaluationController.class
  target/generated-sources/annotations/com/example/lectureevaluationdev/mapper/evaluation/EvaluationMapperImpl.java
Labels: bug, 이해송

#72 Feat/auth
  package-lock.json
  package.json
  src/components/Write/WriteBox.jsx
  src/pages/Login.jsx
  src/pages/Register.jsx
Labels: feat, 정서연

#76 [Feat] 글쓰기 기능 추가
  src/components/Write/StarRating.jsx
  src/components/Write/WriteBox.jsx
Labels: feat, 정서연

#77 [Feat] Detail Page 구현
  src/components/Detail/DetailBox.jsx
  src/pages/Login.jsx
  src/shared/Router.js
Labels: feat, 정서연

#82 [Feat] 메인 페이지 기능 구현
  package.json
  src/components/Main/LikeBox.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
Labels: feat, 이혜영

#94 [Fix#93] 로그인,로그아웃 코드 추가 및 정렬 수정
  src/main/java/com/example/lectureevaluationdev/controller/evaluation/EvaluationController.java
  src/main/java/com/example/lectureevaluationdev/controller/user/UserController.java
  src/main/java/com/example/lectureevaluationdev/dto/evaluation/EvaluationDTO.java
  src/main/java/com/example/lectureevaluationdev/dto/user/UserDTO.java
  src/main/java/com/example/lectureevaluationdev/entity/evaluation/EvaluationEntity.java
  src/main/java/com/example/lectureevaluationdev/entity/user/UserEntity.java
  src/main/java/com/example/lectureevaluationdev/repository/evaluation/EvaluationRepository.java
  src/main/java/com/example/lectureevaluationdev/repository/user/UserRepository.java
  src/main/java/com/example/lectureevaluationdev/service/evaluation/EvaluationService.java
  src/main/java/com/example/lectureevaluationdev/service/user/UserService.java
  src/main/resources/templates/login.html
  src/main/resources/templates/logout.html
  target/classes/com/example/lectureevaluationdev/LectureEvaluationDevApplication.class
  target/classes/com/example/lectureevaluationdev/config/JpaConfig.class
  target/classes/com/example/lectureevaluationdev/controller/evaluation/EvaluationController.class
  target/classes/com/example/lectureevaluationdev/controller/likey/LikeyController.class
  target/classes/com/example/lectureevaluationdev/controller/user/UserController.class
  target/classes/com/example/lectureevaluationdev/dto/evaluation/EvaluationDTO$EvaluationDTOBuilder.class
  target/classes/com/example/lectureevaluationdev/dto/evaluation/EvaluationDTO.class
  target/classes/com/example/lectureevaluationdev/dto/likey/LikeyDTO$LikeyDTOBuilder.class
  target/classes/com/example/lectureevaluationdev/dto/likey/LikeyDTO.class
  target/classes/com/example/lectureevaluationdev/dto/user/UserDTO.class
  target/classes/com/example/lectureevaluationdev/entity/evaluation/EvaluationEntity$EvaluationEntityBuilder.class
  target/classes/com/example/lectureevaluationdev/entity/evaluation/EvaluationEntity.class
  target/classes/com/example/lectureevaluationdev/entity/likey/LikeyEntity$LikeyEntityBuilder.class
  target/classes/com/example/lectureevaluationdev/entity/likey/LikeyEntity.class
  target/classes/com/example/lectureevaluationdev/entity/user/UserEntity$UserEntityBuilder.class
  target/classes/com/example/lectureevaluationdev/entity/user/UserEntity.class
  target/classes/com/example/lectureevaluationdev/mapper/GenericMapper.class
  target/classes/com/example/lectureevaluationdev/mapper/evaluation/EvaluationMapper.class
  target/classes/com/example/lectureevaluationdev/mapper/evaluation/EvaluationMapperImpl.class
  target/classes/com/example/lectureevaluationdev/mapper/likey/LikeyMapper.class
  target/classes/com/example/lectureevaluationdev/mapper/likey/LikeyMapperImpl.class
  target/classes/com/example/lectureevaluationdev/primary/EvaluationResponse$ResponseMap.class
  target/classes/com/example/lectureevaluationdev/primary/EvaluationResponse.class
  target/classes/com/example/lectureevaluationdev/primary/ResponseService.class
  target/classes/com/example/lectureevaluationdev/primary/Role.class
  target/classes/com/example/lectureevaluationdev/repository/evaluation/EvaluationRepository.class
  target/classes/com/example/lectureevaluationdev/repository/likey/LikeyRepository.class
  target/classes/com/example/lectureevaluationdev/repository/user/UserRepository.class
  target/classes/com/example/lectureevaluationdev/service/evaluation/EvaluationService.class
  target/classes/com/example/lectureevaluationdev/service/user/UserService.class
  target/classes/templates/login.html
  target/classes/templates/logout.html
  target/generated-sources/annotations/com/example/lectureevaluationdev/mapper/evaluation/EvaluationMapperImpl.java
  target/generated-sources/annotations/com/example/lectureevaluationdev/mapper/likey/LikeyMapperImpl.java
Labels: bug, 박지원
